### ISSUE TITLE
Eyetribe firmware update tool 

### ISSUE THREAD

**Issue by sjobeek** [purnendu23/EyeTribe#1]
Hello, I hate to pollute your issues with this question, but I've run into issues getting my pytribe device running and believe i need to update my device firmware since its an early unit.

Does anyone on this team happen to have a copy of the firmware update tool they could send me, or know where i could find it?

**Comment by purnendu23** [comment]
Hi sjobeek,
It's been a while ( > 1 year) that I have used eyetribe and am not sure if I will be able to find it for you. But, i will check and see what best i can do.

**Comment by sjobeek** [comment]
I have in fact come across it from another source - thanks again for your help.
